# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

User.create(first_name: "Alberto", last_name: "Zúñiga", password: "password", email: "albertozm2381@gmail.com", profile: 1)
User.create(first_name: "Alberto", last_name: "1", password: "password", email: "ejemplo1@gmail.com", profile: 0)
User.create(first_name: "Alberto", last_name: "2", password: "password", email: "ejemplo2@gmail.com", profile: 0)
User.create(first_name: "Alberto", last_name: "3", password: "password", email: "ejemplo3@gmail.com", profile: 0)
User.create(first_name: "Alberto", last_name: "4", password: "password", email: "ejemplo4@gmail.com", profile: 0)
User.create(first_name: "Alberto", last_name: "5", password: "password", email: "ejemplo5@gmail.com", profile: 0)

Ingredient.create(name: "VINO AÑEJO")
Ingredient.create(name: "COÑAC")
Ingredient.create(name: "MALTA O VERMUT BLANCO")
Ingredient.create(name: "YEMA DE HUEVO")
Ingredient.create(name: "CANELA")
Ingredient.create(name: "MALIBU")
Ingredient.create(name: "JUGO DE PIÑA")
Ingredient.create(name: "CREMA DE COCO")
Ingredient.create(name: "KAHLÚA")
Ingredient.create(name: "VODKA")
Ingredient.create(name: "ESPRESSO")
Ingredient.create(name: "RON BLANCO")
Ingredient.create(name: "JUGO DE LIMON")
Ingredient.create(name: "AZUCAR")
Ingredient.create(name: "TEQUILA")
Ingredient.create(name: "TRIPLE SEC")
Ingredient.create(name: "BERRIES")
Ingredient.create(name: "NARANJA")
Ingredient.create(name: "VINO BLANCO SECO")
Ingredient.create(name: "APEROL")
Ingredient.create(name: "AGUA TONICA")
Ingredient.create(name: "ROMERO FRESCO")
Ingredient.create(name: "WHISKY")
Ingredient.create(name: "VERMUT SECO")
Ingredient.create(name: "CASCARA DE LIMON")
Ingredient.create(name: "CEREZAS")
Ingredient.create(name: "CAMPARI")
Ingredient.create(name: "JUGO DE NARANJA")
Ingredient.create(name: "MENTA")
Ingredient.create(name: "JUGO DE MORTIÑO ROJO")
Ingredient.create(name: "GIN")
Ingredient.create(name: "VERMUT DULCE")
Ingredient.create(name: "CASCARAS DE NARANJA")
Ingredient.create(name: "RON")
Ingredient.create(name: "CURACAO DE NARANJA")
Ingredient.create(name: "GRANADINA")
Ingredient.create(name: "POMELO")
Ingredient.create(name: "ALMIBAR")
Ingredient.create(name: "LICOR DE MELON")
Ingredient.create(name: "JUGO DE LIMON")
Ingredient.create(name: "COINTREAU")
Ingredient.create(name: "VODKA CON JALAPEÑO")
Ingredient.create(name: "ACEITUNAS RELLENAS CON PIMIENTOS")
Ingredient.create(name: "SALSA INGLESA")
Ingredient.create(name: "SALSA DE TABASCO")
Ingredient.create(name: "JEREZ SECO")
Ingredient.create(name: "JUGO DE TOMATE")
Ingredient.create(name: "SAL")
Ingredient.create(name: "TOMATE CHERRY")
Ingredient.create(name: "RODAJAS DE LIMON")
Ingredient.create(name: "GINGER ALE")
Ingredient.create(name: "COHOMBRO")
Ingredient.create(name: "BITTER DE NARANJA")
Ingredient.create(name: "CEREZA AL MARRASQUINO")
Ingredient.create(name: "GAJITO DE LIMON")
Ingredient.create(name: "SAKE")
Ingredient.create(name: "CURACAO AZUL")
Ingredient.create(name: "LICOR DE MELON")
Ingredient.create(name: "CEREZA")
Ingredient.create(name: "NUEZ MOSCADA")
Ingredient.create(name: "FRAMBUESAS FRESCAS")
Ingredient.create(name: "LIMON")
Ingredient.create(name: "MARTINI")
Ingredient.create(name: "GASEOSA DE LIMON")
Ingredient.create(name: "LICOR DE FRAMBUESAS")
Ingredient.create(name: "FRAMBUESA")
Ingredient.create(name: "JUGO DE LIMA")
Ingredient.create(name: "RODAJA DE LIMA")
Ingredient.create(name: "FRESAS")
Ingredient.create(name: "RODAJA DE LIMON")
Ingredient.create(name: "JARABE DE GOMA")

recipe = Recipe.create(name: "VAINA")
recipe.ingredients << Ingredient.find(2)
recipe.ingredients << Ingredient.find(1)
recipe.ingredients << Ingredient.find(3)
recipe.ingredients << Ingredient.find(4)
recipe.ingredients << Ingredient.find(5)

recipe = Recipe.create(name: "PIÑA COLADA")
recipe.ingredients << Ingredient.find(6)
recipe.ingredients << Ingredient.find(7)
recipe.ingredients << Ingredient.find(8)

recipe = Recipe.create(name: "ESPRESSO MARTINI")
recipe.ingredients << Ingredient.find(9)
recipe.ingredients << Ingredient.find(10)
recipe.ingredients << Ingredient.find(11)

recipe = Recipe.create(name: "DAIKIRI")
recipe.ingredients << Ingredient.find(12)
recipe.ingredients << Ingredient.find(13)
recipe.ingredients << Ingredient.find(14)

recipe = Recipe.create(name: "MARGARITA")
recipe.ingredients << Ingredient.find(15)
recipe.ingredients << Ingredient.find(16)
recipe.ingredients << Ingredient.find(13)

recipe = Recipe.create(name: "COSMOPOLITAN")
recipe.ingredients << Ingredient.find(10)
recipe.ingredients << Ingredient.find(16)
recipe.ingredients << Ingredient.find(17)
recipe.ingredients << Ingredient.find(13)
recipe.ingredients << Ingredient.find(30)
recipe.ingredients << Ingredient.find(25)

recipe = Recipe.create(name: "APEROL SPRITZ")
recipe.ingredients << Ingredient.find(18)
recipe.ingredients << Ingredient.find(19)
recipe.ingredients << Ingredient.find(20)
recipe.ingredients << Ingredient.find(21)
recipe.ingredients << Ingredient.find(22)

recipe = Recipe.create(name: "MANHATTAN")
recipe.ingredients << Ingredient.find(23)
recipe.ingredients << Ingredient.find(24)
recipe.ingredients << Ingredient.find(25)
recipe.ingredients << Ingredient.find(26)

recipe = Recipe.create(name: "CAMPARI ORANGE")
recipe.ingredients << Ingredient.find(27)
recipe.ingredients << Ingredient.find(28)
recipe.ingredients << Ingredient.find(18)
recipe.ingredients << Ingredient.find(29)

recipe = Recipe.create(name: "NEGRONI")
recipe.ingredients << Ingredient.find(31)
recipe.ingredients << Ingredient.find(27)
recipe.ingredients << Ingredient.find(32)
recipe.ingredients << Ingredient.find(33)

recipe = Recipe.create(name: "MAI TAI")
recipe.ingredients << Ingredient.find(34)
recipe.ingredients << Ingredient.find(35)
recipe.ingredients << Ingredient.find(13)
recipe.ingredients << Ingredient.find(36)
recipe.ingredients << Ingredient.find(16)
recipe.ingredients << Ingredient.find(29)

recipe = Recipe.create(name: "POMELO RON")
recipe.ingredients << Ingredient.find(37)
recipe.ingredients << Ingredient.find(38)
recipe.ingredients << Ingredient.find(34)
recipe.ingredients << Ingredient.find(29)

recipe = Recipe.create(name: "MELON AGRIDULCE")
recipe.ingredients << Ingredient.find(39)
recipe.ingredients << Ingredient.find(28)
recipe.ingredients << Ingredient.find(40)
recipe.ingredients << Ingredient.find(10)
recipe.ingredients << Ingredient.find(12)

recipe = Recipe.create(name: "NARANJO EN FLOR")
recipe.ingredients << Ingredient.find(31)
recipe.ingredients << Ingredient.find(28)
recipe.ingredients << Ingredient.find(41)
recipe.ingredients << Ingredient.find(24)
recipe.ingredients << Ingredient.find(18)

recipe = Recipe.create(name: "VODKATINI ARDIENTE")
recipe.ingredients << Ingredient.find(42)
recipe.ingredients << Ingredient.find(24)
recipe.ingredients << Ingredient.find(43)

recipe = Recipe.create(name: "BLOODY MARY")
recipe.ingredients << Ingredient.find(44)
recipe.ingredients << Ingredient.find(45)
recipe.ingredients << Ingredient.find(10)
recipe.ingredients << Ingredient.find(46)
recipe.ingredients << Ingredient.find(47)
recipe.ingredients << Ingredient.find(13)
recipe.ingredients << Ingredient.find(48)
recipe.ingredients << Ingredient.find(49)
recipe.ingredients << Ingredient.find(50)

recipe = Recipe.create(name: "MULA DE MOSCU")
recipe.ingredients << Ingredient.find(10)
recipe.ingredients << Ingredient.find(13)
recipe.ingredients << Ingredient.find(51)
recipe.ingredients << Ingredient.find(50)

recipe = Recipe.create(name: "GIN CON COHOMBRO")
recipe.ingredients << Ingredient.find(31)
recipe.ingredients << Ingredient.find(52)
recipe.ingredients << Ingredient.find(21)

recipe = Recipe.create(name: "GLAMUOUR NARANJA")
recipe.ingredients << Ingredient.find(53)
recipe.ingredients << Ingredient.find(31)
recipe.ingredients << Ingredient.find(24)
recipe.ingredients << Ingredient.find(54)
recipe.ingredients << Ingredient.find(55)

recipe = Recipe.create(name: "SAKETINI")
recipe.ingredients << Ingredient.find(31)
recipe.ingredients << Ingredient.find(56)

recipe = Recipe.create(name: "CIELO AZUL")
recipe.ingredients << Ingredient.find(57)
recipe.ingredients << Ingredient.find(31)
recipe.ingredients << Ingredient.find(13)

recipe = Recipe.create(name: "VERDE DULZURA")
recipe.ingredients << Ingredient.find(10)
recipe.ingredients << Ingredient.find(58)
recipe.ingredients << Ingredient.find(59)

recipe = Recipe.create(name: "GIN DEL BOSQUE")
recipe.ingredients << Ingredient.find(31)
recipe.ingredients << Ingredient.find(60)
recipe.ingredients << Ingredient.find(61)
recipe.ingredients << Ingredient.find(29)

recipe = Recipe.create(name: "GIN TONIC ROMERO")
recipe.ingredients << Ingredient.find(31)
recipe.ingredients << Ingredient.find(62)
recipe.ingredients << Ingredient.find(21)

recipe = Recipe.create(name: "MARTINI DE LIMA")
recipe.ingredients << Ingredient.find(63)
recipe.ingredients << Ingredient.find(62)
recipe.ingredients << Ingredient.find(64)
recipe.ingredients << Ingredient.find(50)

recipe = Recipe.create(name: "MARTINI ROJO")
recipe.ingredients << Ingredient.find(63)
recipe.ingredients << Ingredient.find(65)
recipe.ingredients << Ingredient.find(64)
recipe.ingredients << Ingredient.find(66)
recipe.ingredients << Ingredient.find(29)

recipe = Recipe.create(name: "FLAMENCO")
recipe.ingredients << Ingredient.find(10)
recipe.ingredients << Ingredient.find(16)
recipe.ingredients << Ingredient.find(28)
recipe.ingredients << Ingredient.find(67)
recipe.ingredients << Ingredient.find(36)
recipe.ingredients << Ingredient.find(68)

recipe = Recipe.create(name: "MARGARITA FROZEN")
recipe.ingredients << Ingredient.find(15)
recipe.ingredients << Ingredient.find(16)
recipe.ingredients << Ingredient.find(13)
recipe.ingredients << Ingredient.find(69)
recipe.ingredients << Ingredient.find(70)

recipe = Recipe.create(name: "WHISKY SOUR")
recipe.ingredients << Ingredient.find(28)
recipe.ingredients << Ingredient.find(23)
recipe.ingredients << Ingredient.find(71)
recipe.ingredients << Ingredient.find(54)

Rating.create(user_id: 1, recipe_id: 1, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 2, recipe_id: 1, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 3, recipe_id: 1, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 4, recipe_id: 2, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 5, recipe_id: 2, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 6, recipe_id: 2, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 1, recipe_id: 3, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 2, recipe_id: 3, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 3, recipe_id: 3, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 4, recipe_id: 4, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 5, recipe_id: 4, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 6, recipe_id: 4, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 1, recipe_id: 5, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 2, recipe_id: 5, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 3, recipe_id: 5, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 4, recipe_id: 6, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 5, recipe_id: 6, rate: rand(1..5), favorite: rand(0..1))
Rating.create(user_id: 6, recipe_id: 6, rate: rand(1..5), favorite: rand(0..1))